remote_theme: insipx/material-bliss-jekyll-theme
title: Divine Software
tagline: Divine Software | Programming organization
author: TheDebianGuy
description: Divine Software official website

theme: jekyll-theme-midnight